# Generated by Django 6.0 on 2025-12-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='Authors',
        ),
        migrations.AlterModelTable(
            name='book',
            table='Books',
        ),
    ]
